### ISSUE TITLE
Admin frontend sync

### ISSUE THREAD

**Issue by celuchmarek** [tp17-2021/gateway#8]
Keď kliknem na synchronizáciu na admin frontende, nič to nerobí, vypíše to niečo do konzoly a zjavne ma to odhlási, lebo neviem nič iné robiť, kým sa opät neprihlásim. Prikladám aj nejakú foto:

![Screenshot from 2022-03-11 15-43-24](https://user-images.githubusercontent.com/12500066/157889743-a6de8ac4-7e91-4a86-a560-95f0a8960f6c.png)

V db som mal v tom momente 0 hlasov, ale sync service /statistics funguje cez swagger ok.

**Comment by liborduda** [comment]
Toto by už malo fungovať.
